// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cadence-brand/BrandInActionBoard.tsx": () => import("../components/mockups/cadence-brand/BrandInActionBoard.tsx"),
  "./components/mockups/cadence-brand/ColorTypeBoard.tsx": () => import("../components/mockups/cadence-brand/ColorTypeBoard.tsx"),
  "./components/mockups/cadence-brand/GuidelinesBoard.tsx": () => import("../components/mockups/cadence-brand/GuidelinesBoard.tsx"),
  "./components/mockups/cadence-logos/LogoBoard.tsx": () => import("../components/mockups/cadence-logos/LogoBoard.tsx")
};
